//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumeTable
    {
        public int ResumeID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string FileName { get; set; }
        public byte[] FileData { get; set; }
        public string ContentType { get; set; }
    
        public virtual EmployeesTable EmployeesTable { get; set; }
    }
}
