//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RLLProjPractice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccineAvailability
    {
        public int AvailabilityID { get; set; }
        public Nullable<int> VaccineID { get; set; }
        public Nullable<System.DateTime> DateAvailable { get; set; }
        public Nullable<int> QuantityAvailable { get; set; }
    
        public virtual Vaccine Vaccine { get; set; }
    }
}
