//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RllPracticeProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Admin
    {
        public int UserID { get; set; }
        public string Password { get; set; }
        public string Position { get; set; }
        public Nullable<int> CentreID { get; set; }
    
        public virtual VaccineCentre VaccineCentre { get; set; }
    }
}
