//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RllPracticeProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string AadharNumber { get; set; }
        public Nullable<int> RefID { get; set; }
        public string PhoneNumber { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Dose1Status { get; set; }
        public string Dose2Status { get; set; }
        public Nullable<int> Dose1CentreID { get; set; }
        public Nullable<int> Dose2CentreID { get; set; }
        public Nullable<System.DateTime> Dose1Data { get; set; }
        public Nullable<System.DateTime> Dose2Data { get; set; }
        public Nullable<int> Dose1SlotCentreID { get; set; }
        public Nullable<System.DateTime> Dose1SlotDate { get; set; }
        public Nullable<int> Dose2SlotCentreID { get; set; }
        public Nullable<System.DateTime> Dose2SlotDate { get; set; }
        public string Dose1VaccineName { get; set; }
        public string Dose2VaccineName { get; set; }
    
        public virtual Login_Users Login_Users { get; set; }
        public virtual VaccineCentre VaccineCentre { get; set; }
        public virtual Slot Slot { get; set; }
        public virtual VaccineCentre VaccineCentre1 { get; set; }
        public virtual Slot Slot1 { get; set; }
    }
}
