//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RllPracticeProj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineVaccineEntities : DbContext
    {
        public OnlineVaccineEntities()
            : base("name=OnlineVaccineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Login_Admin> Login_Admin { get; set; }
        public virtual DbSet<Login_Users> Login_Users { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Slot> Slots { get; set; }
        public virtual DbSet<VaccineCentre> VaccineCentres { get; set; }
    }
}
