//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RllPracticeProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccineCentre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VaccineCentre()
        {
            this.Login_Admin = new HashSet<Login_Admin>();
            this.Members = new HashSet<Member>();
            this.Members1 = new HashSet<Member>();
            this.Slots = new HashSet<Slot>();
        }
    
        public int CentreID { get; set; }
        public string Hospital_Name { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public string Pin_code { get; set; }
        public string VaccineName { get; set; }
        public Nullable<decimal> VaccineCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login_Admin> Login_Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slot> Slots { get; set; }
    }
}
